// <auto-generated />
namespace Gazi.Kazan.Myo.Araba.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DetayTablosuEklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DetayTablosuEklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "202005181937495_DetayTablosuEklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
